# リリースブランチをmasterから切ってtkbをマージする
# リリースブランチのプルリクを出す

name: release branch merge

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      version:
        description: 'バージョン'
        required: true
        default: '1.0.0'
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # https://zenn.dev/satococoa/articles/e026c0689e5678
          ref: master
      - name: create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}
      - name: create pull request for release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout tkb/${{ github.event.inputs.version }} 
          git push
          hub pull-request -b tkb/${{ github.event.inputs.version }} -m "tkb/${{ github.event.inputs.version }}"
      - name: merge tkb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge tkb/${{ github.event.inputs.version }} --merge
