name: Manual Release Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: '名前を入力してください。'
        default: 'Watanabe'
        required: true
      age:
        description: '年齢を入力してください'
        default: '12'

jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Get Value
        run: |
          echo ${{ github.event.inputs.name }}
          echo ${{ github.event.inputs.age }}